language: node_js
node_js:
- '0.10'
verbose: true
os: linux
before_script:
- npm install -g harp
- chmod +x ./deploy.sh
script: true
after_success: "./deploy.sh"
env:
  global:
    secure: gAhW4vC2iMejPzIXssmsGihISyHSn9ZiFK2S4xoz/q4qcM9LBQlc80LPs4k3Ce9xvGCtm0Rawhz0oMUN0JhyVMN/7RGrDBbPtBkS1jBL+fjfz10qqFuGcPD5eronH1ugjwEjKKlkj46/BxwhAYbou0/lhhvmnFVWoD6u7maG5MKjl91FzT3SfoSvlPs9BPAHj8LMvWAUrB0vBvwPE4nuR2dSISf9wqxDMg7rOFKhSZGf6NWpz4RGl7iaClMzBrrIFDFlNYhxmSmwlOl/BmP0y0gVstUGl0KiWACY2DF+KaDOFbgewdPsG0Zz61ki7uoFaU3Z9KVKfSnVpaz/6RakJKgOFXwqavvZfpn5yMU9s7blHJrYklAUial6a1vYICb6CacS73v3TyWQuVSiqk9knZOVUkn+v6Pe26Txvzrz8FQhUjd7ua87nHu44fnsW/GMBRazoqySO3SkJ0we00D93j0x8G3LWeW8Vtqs+qUixRADtld7D2FjPPRNM6ZKL6JGKjC0qhhDE2hidLkd1xiY7VXuBnm4xKeEsjxxgRRK/9CRfQv1fAxEWWlz7hnYOzsLT31HY1YFMMHfftQxH9SpX1HgHE2cCfSx/AbMMWMvmLVnuy65wgihb/79jIMtbTNtCCV1duOZ/dyLrt5I1tOf+PwKjpJMhUnXDe1JEBNQwcE=
